#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#define MAX 7800

void FillRand(float *, int);
void FillIncr(float *, int);
void FillDeor(float *, int);
void FillEqual(float *, int);
void Almost(float *, int);
void Swap(float *, float *);
int Cheak(float *, int);
void AdvancedBubleSort(float *, int);
void SelectSort(float *, int);
void InsertSort(float *, int);
void Merge(float *, int, int);
void MergeSort(float *, int);
void QuickSort(float *, int);
void HeapCorrection(float *, int, int);
void HeapSort (float *, int);